#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://47.108.173.85:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: 1439116557@zhouSE
#  cloud:
#      nacos:
#        discovery:
#          server-addr: 47.108.173.85:8848
#  application:
#    name: gulimall-coupon
#
#
##暴露/actuator/sentinel端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'